[project]
authors = ["Hannah Zafar <hannah.zafar@nasa.gov>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "micasa-virtualizarr"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.5,<3"
pandas = ">=2.2.3,<3"
xarray = ">=2025.4.0,<2026"
ipykernel = ">=6.29.5,<7"
matplotlib = ">=3.10.1,<4"
python = ">=3.12.10,<3.13"
netcdf4 = ">=1.7.2,<2"
virtualizarr = ">=1.3.2,<2"
h5netcdf = ">=1.6.1,<2"
icechunk = ">=0.2.15,<0.3"
kerchunk = ">=0.2.8,<0.3"
dask = ">=2025.4.1,<2026"
